import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Posts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  bg-zinc-100 text-zinc-900 flex justify-center`}
      >
        <div className="container flex flex-col min-h-screen bg-white  border-l border-r px-5 sm:px-10 md:px-15 lg:px-20">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
